### ISSUE TITLE
[FEATURE] シンプルでかっこいい個人の自己紹介サイトを作成したい

### ISSUE THREAD

**Issue by Tsukumo3** [Tsukumo3/Tsukumo3.github.io#17]
## 目的

自己紹介サイトを自分で作りたい

## ゴール

シンプルでかっこいい自己紹介サイトができること

## 実現する方法

1. どういう状態になればシンプルでかっこいいのか？を定義する
2. 見てもらう人のターゲットを決める
3. コンテンツを作成する（写真、名前、連絡先、自己紹介文、スキル、経験、誇り、プロジェクト
4. ワイヤーフレームとデザインを考える
5. 静的なウェブサイトを作成する（技術選定も含めて
6. PC, Mobileに対応させる
7. テストとデバッグ
8. デプロイ

**Comment by Tsukumo3** [comment]
# ベースプロジェクトの作成

- GitHub.ioでViteのデプロイ
    - https://ja.vitejs.dev/guide/static-deploy

**Comment by Tsukumo3** [comment]
## GitHub ActionでViteプロジェクトの対応

`.github/workflows/static.yml

```yml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master, develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```
